### PR TITLE
Plone 5.2/Python 3 compabitlity.

### PR DESCRIPTION
**Pull request by zopyx**

### CODE REVIEW

**Comment by zopyx** [comment]
All tests passing

https://travis-ci.org/collective/plone.app.changeownership/builds/579672163

**Review by tomgross — CHANGES_REQUESTED** [review]
If Python 3 compatibility is claimed it should be tested through travis.

**Comment by zopyx** [comment]
All green with 5.2/python 3.6: 

https://travis-ci.org/collective/plone.app.changeownership/builds/579756825

**Review by tomgross — APPROVED** [review]
LGTM

**Pull request merged**
